---
# tasks file for app
- name: Show info about the env this host belongs to
  debug:
    msg: "This host is in {{ env }} environment."
- import_tasks: ruby.yml
  tags:
    - app-ruby

- import_tasks: puma.yml
  tags:
    - app_puma
