Vagrant.configure("2") do |config|

  config.vm.provider :virtualbox do |v|
    v.memory = 512 #ram memory for vm
  end

  config.vm.define "dbserver" do |db|
    db.vm.box = "ubuntu/xenial64"
    db.vm.hostname = "dbserver"  #name of VM
    db.vm.network :private_network, ip: "10.10.10.15"

    db.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbooks/site.yml"
      ansible.groups = {
      "db" => ["dbserver"],
      "db:vars" => {"mongo_bind_ip" => "0.0.0.0"}
      }
    end
  end

  config.vm.define "appserver" do |app|
    app.vm.box = "ubuntu/xenial64"  # box name - image of VM
    app.vm.hostname = "appserver"
    app.vm.network :private_network, ip: "10.10.10.25" # IP of internal interface

    app.vm.provision "ansible" do |ansible|
     ansible.playbook = "playbooks/site.yml"
     ansible.groups = {
     "app" => ["appserver"],
     "app:vars" => { "db_host" => "10.10.10.15"}
     }
     ansible.extra_vars = {
       "deploy_user" => "ubuntu"
     }
   end
  end
end
